### ISSUE TITLE
可以分享一份有数据的sql嘛

### ISSUE THREAD

**Issue by qinglt** [XMMarlowe/SpringBoot-VUE-Music#1]

**Comment by XMMarlowe** [comment]
有个爬虫的接口 你可以调用一下&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 情话dr ***@***.***&gt;
发送时间: 2022年4月25日 18:03
收件人: XMMarlowe/SpringBoot-VUE-Music ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [XMMarlowe/SpringBoot-VUE-Music] 可以分享一份有数据的sql嘛 (Issue #1)

**Comment by Crane1043778796** [comment]
> 有个爬虫的接口 你可以调用一下&nbsp; 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 情话dr ***@***.***&gt; 发送时间: 2022年4月25日 18:03 收件人: XMMarlowe/SpringBoot-VUE-Music ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [XMMarlowe/SpringBoot-VUE-Music] 可以分享一份有数据的sql嘛 (Issue #1)

这个接口在哪

**Comment by XMMarlowe** [comment]
src/main/java/com/marlowe/music/reptile/ReptileController.java
